# kinova_number_of_robots: 2
# kinova_robots:
#   - serial: PJ00900006027686
#     type: j2n6s300
#     name: left
#   - serial: PJ00900006450593
#     type: j2n6s300
#     name: right

left_arm:
  serial: PJ00900006027686
  type: j2n6s300
  name: left

right_arm: 
  serial: PJ00900006450593
  type: j2n6s300
  name: right
